WC Docker: Build from php-7.2-fpm to allow easy switching WP version
We will clone the WordPress's Github repo. This allow to change the current WordPress version by just checking out the required branch (like `git checkout 5.2-branch`).

Also added some steps to install required dependencies.

diff --git a/.docker/Dockerfile b/.docker/Dockerfile
--- a/.docker/Dockerfile
+++ b/.docker/Dockerfile
@@ -1,11 +1,70 @@
-FROM wordpress:5.0.3-fpm
+FROM php:7.2-fpm
 
-# We store files in `mu` directory to make it consistent with production.
-RUN mkdir -p /usr/src/public_html/mu/ && mv /usr/src/wordpress/* /usr/src/public_html/mu
+# ----- Start section copied from https://github.com/docker-library/wordpress/blob/master/php7.2/fpm/Dockerfile ----- #
+
+# install the PHP extensions we need
+RUN set -ex; \
+	\
+	savedAptMark="$(apt-mark showmanual)"; \
+	\
+	apt-get update; \
+	apt-get install -y --no-install-recommends \
+		libjpeg-dev \
+		libpng-dev \
+	; \
+	\
+	docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr; \
+	docker-php-ext-install gd mysqli opcache zip; \
+	\
+# reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies
+	apt-mark auto '.*' > /dev/null; \
+	apt-mark manual $savedAptMark; \
+	ldd "$(php -r 'echo ini_get("extension_dir");')"/*.so \
+		| awk '/=>/ { print $3 }' \
+		| sort -u \
+		| xargs -r dpkg-query -S \
+		| cut -d: -f1 \
+		| sort -u \
+		| xargs -rt apt-mark manual; \
+	\
+	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
+	rm -rf /var/lib/apt/lists/*
+
+# set recommended PHP.ini settings
+# see https://secure.php.net/manual/en/opcache.installation.php
+RUN { \
+		echo 'opcache.memory_consumption=128'; \
+		echo 'opcache.interned_strings_buffer=8'; \
+		echo 'opcache.max_accelerated_files=4000'; \
+		echo 'opcache.revalidate_freq=2'; \
+		echo 'opcache.fast_shutdown=1'; \
+		echo 'opcache.enable_cli=1'; \
+	} > /usr/local/etc/php/conf.d/opcache-recommended.ini
+# https://codex.wordpress.org/Editing_wp-config.php#Configure_Error_Logging
+RUN { \
+		echo 'error_reporting = 4339'; \
+		echo 'display_errors = Off'; \
+		echo 'display_startup_errors = Off'; \
+		echo 'log_errors = On'; \
+		echo 'error_log = /dev/stderr'; \
+		echo 'log_errors_max_len = 1024'; \
+		echo 'ignore_repeated_errors = On'; \
+		echo 'ignore_repeated_source = Off'; \
+		echo 'html_errors = Off'; \
+	} > /usr/local/etc/php/conf.d/error-logging.ini
+
+# ----- Copied section ends ----- #
+
+RUN apt-get update
+
+# Download WordPress source code. We are downloading from git so that we can checkout different WordPress versions by
+# just checking out the branch.
+RUN apt-get install git -y
+RUN mkdir -p /usr/src/public_html/ && cd /usr/src/public_html/ && git clone git://github.com/WordPress/WordPress.git mu
+RUN cd /usr/src/public_html/mu && git checkout 5.2-branch
 WORKDIR /usr/src/public_html
 
 # Install and configure nginx
-RUN apt-get update
 RUN apt-get install nginx -y
 COPY nginx.conf /etc/nginx/sites-enabled/wordcamp.conf
 COPY php-fpm.conf /usr/local/etc/php-fpm.d/zz-www.conf
